// Generated by scripts/generate-indicator-pages.ts — do not edit by hand.
export const indicatorSidebar = [
  {
    items: [
      {
        link: '/indicators/trend/adx',
        text: 'ADX',
      },
      {
        link: '/indicators/trend/adxr',
        text: 'ADXR',
      },
      {
        link: '/indicators/trend/alma',
        text: 'ALMA',
      },
      {
        link: '/indicators/trend/aroon',
        text: 'Aroon',
      },
      {
        link: '/indicators/trend/breakout-bar-low',
        text: 'BreakoutBarLow',
      },
      {
        link: '/indicators/trend/chande-kroll-stop',
        text: 'Chande Kroll Stop',
      },
      {
        link: '/indicators/trend/chandelier-exit',
        text: 'Chandelier Exit',
      },
      {
        link: '/indicators/trend/dema',
        text: 'DEMA',
      },
      {
        link: '/indicators/trend/dma',
        text: 'DMA',
      },
      {
        link: '/indicators/trend/dx',
        text: 'DX',
      },
      {
        link: '/indicators/trend/ema',
        text: 'EMA',
      },
      {
        link: '/indicators/trend/frama',
        text: 'FRAMA',
      },
      {
        link: '/indicators/trend/gann-hilo',
        text: 'Gann HiLo Activator',
      },
      {
        link: '/indicators/trend/higher-low-trail',
        text: 'HigherLowTrail',
      },
      {
        link: '/indicators/trend/hma',
        text: 'HMA',
      },
      {
        link: '/indicators/trend/ht-trendline',
        text: 'HT Trendline',
      },
      {
        link: '/indicators/trend/ichimoku',
        text: 'Ichimoku Cloud',
      },
      {
        link: '/indicators/trend/kama',
        text: 'KAMA',
      },
      {
        link: '/indicators/trend/linreg',
        text: 'LINREG',
      },
      {
        link: '/indicators/trend/mama',
        text: 'MAMA',
      },
      {
        link: '/indicators/trend/mcginley-dynamic',
        text: 'MD',
      },
      {
        link: '/indicators/trend/psar',
        text: 'PSAR',
      },
      {
        link: '/indicators/trend/rwi',
        text: 'Random Walk Index',
      },
      {
        link: '/indicators/trend/rma',
        text: 'RMA',
      },
      {
        link: '/indicators/trend/sma',
        text: 'SMA',
      },
      {
        link: '/indicators/trend/sma15',
        text: 'SMA15',
      },
      {
        link: '/indicators/trend/supersmoother',
        text: 'SuperSmoother',
      },
      {
        link: '/indicators/trend/supertrend',
        text: 'SuperTrend',
      },
      {
        link: '/indicators/trend/swing-high',
        text: 'SwingHigh',
      },
      {
        link: '/indicators/trend/swing-low',
        text: 'SwingLow',
      },
      {
        link: '/indicators/trend/t3',
        text: 'T3',
      },
      {
        link: '/indicators/trend/tema',
        text: 'TEMA',
      },
      {
        link: '/indicators/trend/trima',
        text: 'TRIMA',
      },
      {
        link: '/indicators/trend/vhf',
        text: 'Vertical Horizontal Filter',
      },
      {
        link: '/indicators/trend/vidya',
        text: 'VIDYA',
      },
      {
        link: '/indicators/trend/volatility-stop',
        text: 'Volatility Stop',
      },
      {
        link: '/indicators/trend/vortex',
        text: 'Vortex Indicator',
      },
      {
        link: '/indicators/trend/vwap',
        text: 'VWAP',
      },
      {
        link: '/indicators/trend/alligator',
        text: 'Williams Alligator',
      },
      {
        link: '/indicators/trend/wma',
        text: 'WMA',
      },
      {
        link: '/indicators/trend/wsma',
        text: 'WSMA',
      },
      {
        link: '/indicators/trend/zigzag',
        text: 'ZigZag',
      },
      {
        link: '/indicators/trend/zlema',
        text: 'ZLEMA',
      },
    ],
    text: 'Trend Indicators',
  },
  {
    items: [
      {
        link: '/indicators/momentum/ac',
        text: 'AC',
      },
      {
        link: '/indicators/momentum/ao',
        text: 'AO',
      },
      {
        link: '/indicators/momentum/apo',
        text: 'APO',
      },
      {
        link: '/indicators/momentum/asi',
        text: 'ASI',
      },
      {
        link: '/indicators/momentum/bop',
        text: 'BOP',
      },
      {
        link: '/indicators/momentum/cci',
        text: 'CCI',
      },
      {
        link: '/indicators/momentum/cfo',
        text: 'CFO',
      },
      {
        link: '/indicators/momentum/cg',
        text: 'CG',
      },
      {
        link: '/indicators/momentum/cmo',
        text: 'CMO',
      },
      {
        link: '/indicators/momentum/connors-rsi',
        text: 'ConnorsRSI',
      },
      {
        link: '/indicators/momentum/coppock',
        text: 'Coppock Curve',
      },
      {
        link: '/indicators/momentum/demarker',
        text: 'DeMarker',
      },
      {
        link: '/indicators/momentum/disparity-index',
        text: 'DI',
      },
      {
        link: '/indicators/momentum/derivative-oscillator',
        text: 'DOSC',
      },
      {
        link: '/indicators/momentum/dpo',
        text: 'DPO',
      },
      {
        link: '/indicators/momentum/elder-ray',
        text: 'Elder Ray',
      },
      {
        link: '/indicators/momentum/er',
        text: 'ER',
      },
      {
        link: '/indicators/momentum/fisher',
        text: 'Fisher Transform',
      },
      {
        link: '/indicators/momentum/ibs',
        text: 'IBS',
      },
      {
        link: '/indicators/momentum/imi',
        text: 'IMI',
      },
      {
        link: '/indicators/momentum/kst',
        text: 'KST',
      },
      {
        link: '/indicators/momentum/laguerre-rsi',
        text: 'Laguerre RSI',
      },
      {
        link: '/indicators/momentum/macd',
        text: 'MACD',
      },
      {
        link: '/indicators/momentum/mfi',
        text: 'MFI',
      },
      {
        link: '/indicators/momentum/mom',
        text: 'MOM',
      },
      {
        link: '/indicators/momentum/obv',
        text: 'OBV',
      },
      {
        link: '/indicators/momentum/pgo',
        text: 'PGO',
      },
      {
        link: '/indicators/momentum/pmo',
        text: 'PMO',
      },
      {
        link: '/indicators/momentum/ppo',
        text: 'PPO',
      },
      {
        link: '/indicators/momentum/premier-stochastic',
        text: 'Premier Stochastic',
      },
      {
        link: '/indicators/momentum/psl',
        text: 'PSL',
      },
      {
        link: '/indicators/momentum/qqe',
        text: 'QQE',
      },
      {
        link: '/indicators/momentum/qstick',
        text: 'Qstick',
      },
      {
        link: '/indicators/momentum/rci',
        text: 'RCI',
      },
      {
        link: '/indicators/momentum/rei',
        text: 'REI',
      },
      {
        link: '/indicators/momentum/rmi',
        text: 'RMI',
      },
      {
        link: '/indicators/momentum/roc',
        text: 'ROC',
      },
      {
        link: '/indicators/momentum/rsi',
        text: 'RSI',
      },
      {
        link: '/indicators/momentum/rvgi',
        text: 'RVGI',
      },
      {
        link: '/indicators/momentum/smi',
        text: 'SMI',
      },
      {
        link: '/indicators/momentum/stc',
        text: 'STC',
      },
      {
        link: '/indicators/momentum/stoch',
        text: 'Stochastic',
      },
      {
        link: '/indicators/momentum/stochrsi',
        text: 'StochRSI',
      },
      {
        link: '/indicators/momentum/tds',
        text: 'TDS',
      },
      {
        link: '/indicators/momentum/trix',
        text: 'TRIX',
      },
      {
        link: '/indicators/momentum/tsi',
        text: 'TSI',
      },
      {
        link: '/indicators/momentum/ultosc',
        text: 'ULTOSC',
      },
      {
        link: '/indicators/momentum/waddah-attar',
        text: 'WAE',
      },
      {
        link: '/indicators/momentum/wavetrend',
        text: 'WaveTrend',
      },
      {
        link: '/indicators/momentum/willr',
        text: 'Williams %R',
      },
    ],
    text: 'Momentum Indicators',
  },
  {
    items: [
      {
        link: '/indicators/volatility/percent-b',
        text: '%B',
      },
      {
        link: '/indicators/volatility/abands',
        text: 'ABANDS',
      },
      {
        link: '/indicators/volatility/atr',
        text: 'ATR',
      },
      {
        link: '/indicators/volatility/bbw',
        text: 'BBW',
      },
      {
        link: '/indicators/volatility/bbands',
        text: 'Bollinger Bands',
      },
      {
        link: '/indicators/volatility/cvi',
        text: 'Chaikin Volatility',
      },
      {
        link: '/indicators/volatility/chop',
        text: 'Choppiness Index',
      },
      {
        link: '/indicators/volatility/donchian-channels',
        text: 'Donchian Channels',
      },
      {
        link: '/indicators/volatility/gapo',
        text: 'Gopalakrishnan Range Index',
      },
      {
        link: '/indicators/volatility/iqr',
        text: 'IQR',
      },
      {
        link: '/indicators/volatility/keltner-channels',
        text: 'Keltner Channels',
      },
      {
        link: '/indicators/volatility/mad',
        text: 'MAD',
      },
      {
        link: '/indicators/volatility/mass-index',
        text: 'Mass Index',
      },
      {
        link: '/indicators/volatility/natr',
        text: 'NATR',
      },
      {
        link: '/indicators/volatility/projection-oscillator',
        text: 'PO',
      },
      {
        link: '/indicators/volatility/rogers-satchell',
        text: 'Rogers-Satchell Volatility',
      },
      {
        link: '/indicators/volatility/rvi',
        text: 'RVI',
      },
      {
        link: '/indicators/volatility/tr',
        text: 'TR',
      },
      {
        link: '/indicators/volatility/ttm-squeeze',
        text: 'TTM Squeeze',
      },
      {
        link: '/indicators/volatility/ulcer-index',
        text: 'Ulcer Index',
      },
    ],
    text: 'Volatility Indicators',
  },
  {
    items: [
      {
        link: '/indicators/volume/ad',
        text: 'AD',
      },
      {
        link: '/indicators/volume/adosc',
        text: 'ADOSC',
      },
      {
        link: '/indicators/volume/cmf',
        text: 'CMF',
      },
      {
        link: '/indicators/volume/emv',
        text: 'EMV',
      },
      {
        link: '/indicators/volume/force-index',
        text: 'ForceIndex',
      },
      {
        link: '/indicators/volume/kvo',
        text: 'KVO',
      },
      {
        link: '/indicators/volume/marketfi',
        text: 'MARKETFI',
      },
      {
        link: '/indicators/volume/nvi',
        text: 'NVI',
      },
      {
        link: '/indicators/volume/pvi',
        text: 'PVI',
      },
      {
        link: '/indicators/volume/pvo',
        text: 'PVO',
      },
      {
        link: '/indicators/volume/pvt',
        text: 'PVT',
      },
      {
        link: '/indicators/volume/vroc',
        text: 'VROC',
      },
      {
        link: '/indicators/volume/vwma',
        text: 'VWMA',
      },
      {
        link: '/indicators/volume/wad',
        text: 'WAD',
      },
    ],
    text: 'Volume Indicators',
  },
];
