/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export class ExternalObject<T> {
  readonly '': {
    readonly '': unique symbol;
    [K: symbol]: T;
  };
}
export const enum MacdIndicatorEnum {
  EMA = 0,
  DEMA = 1,
}
export interface MacdConfig {
  longInterval: number;
  shortInterval: number;
  signalInterval: number;
  indicator: MacdIndicatorEnum;
}
export interface MacdResult {
  histogram: number;
  macd: number;
  signal: number;
}
export class DEMA {
  constructor(interval: number);
  update(price: number): number;
  getResult(): number;
  get isStable(): boolean;
  get result(): number;
  get lowest(): number;
  get highest(): number;
}
export class EMA {
  constructor(interval: number);
  update(price: number): number;
  getResult(): number;
  get isStable(): boolean;
  get result(): number;
}
export class MACD {
  constructor(config: MacdConfig);
  update(price: number): MacdResult;
  fastUpdate(price: number): boolean;
  getResult(): MacdResult;
  get isStable(): boolean;
  get result(): MacdResult;
}
