/**
 * Mapping of S&P 500 tickers to their GICS sector abbreviation.
 *
 * Sector labels:
 *   Tech        – Information Technology
 *   Health      – Health Care
 *   Finance     – Financials
 *   Comm        – Communication Services
 *   Consumer    – Consumer Discretionary
 *   Staples     – Consumer Staples
 *   Industrial  – Industrials
 *   Energy      – Energy
 *   Utility     – Utilities
 *   Material    – Materials
 *   Real Estate – Real Estate
 */
export const SP500_SECTORS: Record<string, string> = {
  // Information Technology
  AAPL: 'Tech',
  ACN: 'Tech',
  ADBE: 'Tech',
  ADI: 'Tech',
  ADP: 'Tech',
  ADSK: 'Tech',
  AKAM: 'Tech',
  AMAT: 'Tech',
  AMD: 'Tech',
  ANET: 'Tech',
  ANSS: 'Tech',
  APH: 'Tech',
  AVGO: 'Tech',
  BR: 'Tech',
  CDNS: 'Tech',
  CDW: 'Tech',
  CRM: 'Tech',
  CRWD: 'Tech',
  CSCO: 'Tech',
  CSGP: 'Tech',
  CTSH: 'Tech',
  DXCM: 'Tech',
  DXC: 'Tech',
  ENPH: 'Tech',
  EPAM: 'Tech',
  FDS: 'Tech',
  FFIV: 'Tech',
  FIS: 'Tech',
  FISV: 'Tech',
  FLT: 'Tech',
  FTNT: 'Tech',
  FTV: 'Tech',
  GEN: 'Tech',
  GLW: 'Tech',
  GPN: 'Tech',
  HPE: 'Tech',
  HPQ: 'Tech',
  IBM: 'Tech',
  INTC: 'Tech',
  INTU: 'Tech',
  IT: 'Tech',
  JKHY: 'Tech',
  JNPR: 'Tech',
  KEYS: 'Tech',
  KLAC: 'Tech',
  LRCX: 'Tech',
  MCHP: 'Tech',
  MPWR: 'Tech',
  MSFT: 'Tech',
  MSI: 'Tech',
  MU: 'Tech',
  NOW: 'Tech',
  NTAP: 'Tech',
  NVDA: 'Tech',
  NXPI: 'Tech',
  ON: 'Tech',
  ORCL: 'Tech',
  PAYC: 'Tech',
  PAYX: 'Tech',
  PTC: 'Tech',
  PYPL: 'Tech',
  QCOM: 'Tech',
  QRVO: 'Tech',
  ROP: 'Tech',
  SMCI: 'Tech',
  SNPS: 'Tech',
  STX: 'Tech',
  SWKS: 'Tech',
  TEL: 'Tech',
  TER: 'Tech',
  TRMB: 'Tech',
  TXN: 'Tech',
  TYL: 'Tech',
  VLTO: 'Tech',
  VRSN: 'Tech',
  WDC: 'Tech',
  ZBRA: 'Tech',
  CDAY: 'Tech',

  // Health Care
  ABBV: 'Health',
  ABT: 'Health',
  ALGN: 'Health',
  AMGN: 'Health',
  BAX: 'Health',
  BDX: 'Health',
  BIO: 'Health',
  BIIB: 'Health',
  BMY: 'Health',
  BSX: 'Health',
  CAH: 'Health',
  CI: 'Health',
  CNC: 'Health',
  COO: 'Health',
  CRL: 'Health',
  CVS: 'Health',
  DHR: 'Health',
  DGX: 'Health',
  DVA: 'Health',
  EW: 'Health',
  GEHC: 'Health',
  GILD: 'Health',
  HCA: 'Health',
  HOLX: 'Health',
  HSIC: 'Health',
  HUM: 'Health',
  IDXX: 'Health',
  ILMN: 'Health',
  INCY: 'Health',
  IQV: 'Health',
  ISRG: 'Health',
  JNJ: 'Health',
  KVUE: 'Health',
  LH: 'Health',
  LLY: 'Health',
  MCK: 'Health',
  MDT: 'Health',
  MOH: 'Health',
  MRK: 'Health',
  MRNA: 'Health',
  MTD: 'Health',
  OGN: 'Health',
  PFE: 'Health',
  PKI: 'Health',
  REGN: 'Health',
  RMD: 'Health',
  RVTY: 'Health',
  STE: 'Health',
  SYK: 'Health',
  TECH: 'Health',
  TFX: 'Health',
  TMO: 'Health',
  UHS: 'Health',
  UNH: 'Health',
  VRTX: 'Health',
  VTRS: 'Health',
  WAT: 'Health',
  WST: 'Health',
  XRAY: 'Health',
  ZBH: 'Health',
  ZTS: 'Health',

  // Financials
  AFL: 'Finance',
  AIG: 'Finance',
  AIZ: 'Finance',
  AJG: 'Finance',
  ALL: 'Finance',
  AMP: 'Finance',
  AON: 'Finance',
  AXP: 'Finance',
  BAC: 'Finance',
  BEN: 'Finance',
  BK: 'Finance',
  BLK: 'Finance',
  'BRK.B': 'Finance',
  BRO: 'Finance',
  C: 'Finance',
  CB: 'Finance',
  CBOE: 'Finance',
  CFG: 'Finance',
  CINF: 'Finance',
  CMA: 'Finance',
  CME: 'Finance',
  COF: 'Finance',
  DFS: 'Finance',
  FITB: 'Finance',
  GL: 'Finance',
  GS: 'Finance',
  HBAN: 'Finance',
  ICE: 'Finance',
  IVZ: 'Finance',
  JPM: 'Finance',
  KEY: 'Finance',
  L: 'Finance',
  LNC: 'Finance',
  MA: 'Finance',
  MCO: 'Finance',
  MET: 'Finance',
  MKTX: 'Finance',
  MMC: 'Finance',
  MS: 'Finance',
  MSCI: 'Finance',
  MTB: 'Finance',
  NDAQ: 'Finance',
  NTRS: 'Finance',
  PFG: 'Finance',
  PGR: 'Finance',
  PNC: 'Finance',
  PRU: 'Finance',
  RE: 'Finance',
  RF: 'Finance',
  RJF: 'Finance',
  SCHW: 'Finance',
  SPGI: 'Finance',
  STT: 'Finance',
  SYF: 'Finance',
  TFC: 'Finance',
  TROW: 'Finance',
  TRV: 'Finance',
  USB: 'Finance',
  V: 'Finance',
  WFC: 'Finance',
  WRB: 'Finance',
  WTW: 'Finance',
  ZION: 'Finance',

  // Communication Services
  CHTR: 'Comm',
  CMCSA: 'Comm',
  DIS: 'Comm',
  EA: 'Comm',
  FOX: 'Comm',
  FOXA: 'Comm',
  GOOG: 'Comm',
  GOOGL: 'Comm',
  IPG: 'Comm',
  LYV: 'Comm',
  META: 'Comm',
  MTCH: 'Comm',
  NFLX: 'Comm',
  NWS: 'Comm',
  NWSA: 'Comm',
  OMC: 'Comm',
  PARA: 'Comm',
  T: 'Comm',
  TMUS: 'Comm',
  TTWO: 'Comm',
  VZ: 'Comm',
  WBD: 'Comm',

  // Consumer Discretionary
  ALK: 'Consumer',
  AMZN: 'Consumer',
  APTV: 'Consumer',
  AZO: 'Consumer',
  BBWI: 'Consumer',
  BBY: 'Consumer',
  BKNG: 'Consumer',
  BWA: 'Consumer',
  CCL: 'Consumer',
  CMG: 'Consumer',
  CZR: 'Consumer',
  DAL: 'Consumer',
  DECK: 'Consumer',
  DG: 'Consumer',
  DHI: 'Consumer',
  DLTR: 'Consumer',
  DPZ: 'Consumer',
  DRI: 'Consumer',
  EBAY: 'Consumer',
  ETSY: 'Consumer',
  EXPE: 'Consumer',
  F: 'Consumer',
  GM: 'Consumer',
  GPC: 'Consumer',
  GRMN: 'Consumer',
  HAS: 'Consumer',
  HD: 'Consumer',
  KMX: 'Consumer',
  LEN: 'Consumer',
  LKQ: 'Consumer',
  LOW: 'Consumer',
  LULU: 'Consumer',
  LUV: 'Consumer',
  LVS: 'Consumer',
  LW: 'Consumer',
  MAR: 'Consumer',
  MCD: 'Consumer',
  MGM: 'Consumer',
  MHK: 'Consumer',
  NCLH: 'Consumer',
  NKE: 'Consumer',
  NVR: 'Consumer',
  NWL: 'Consumer',
  ORLY: 'Consumer',
  PHM: 'Consumer',
  POOL: 'Consumer',
  PVH: 'Consumer',
  RCL: 'Consumer',
  RL: 'Consumer',
  ROST: 'Consumer',
  SBUX: 'Consumer',
  TGT: 'Consumer',
  TJX: 'Consumer',
  TPR: 'Consumer',
  TSCO: 'Consumer',
  TSLA: 'Consumer',
  UAL: 'Consumer',
  ULTA: 'Consumer',
  VFC: 'Consumer',
  WHR: 'Consumer',
  WYNN: 'Consumer',
  YUM: 'Consumer',

  // Consumer Staples
  ADM: 'Staples',
  'BF.B': 'Staples',
  BG: 'Staples',
  CAG: 'Staples',
  CHD: 'Staples',
  CL: 'Staples',
  CLX: 'Staples',
  COST: 'Staples',
  CPB: 'Staples',
  EL: 'Staples',
  GIS: 'Staples',
  HRL: 'Staples',
  HSY: 'Staples',
  K: 'Staples',
  KDP: 'Staples',
  KHC: 'Staples',
  KMB: 'Staples',
  KO: 'Staples',
  KR: 'Staples',
  MDLZ: 'Staples',
  MKC: 'Staples',
  MNST: 'Staples',
  MO: 'Staples',
  PEP: 'Staples',
  PG: 'Staples',
  PM: 'Staples',
  SJM: 'Staples',
  STZ: 'Staples',
  SYY: 'Staples',
  TAP: 'Staples',
  TSN: 'Staples',
  WBA: 'Staples',
  WMT: 'Staples',

  // Industrials
  ALLE: 'Industrial',
  AME: 'Industrial',
  AOS: 'Industrial',
  BA: 'Industrial',
  CARR: 'Industrial',
  CAT: 'Industrial',
  CHRW: 'Industrial',
  CMI: 'Industrial',
  CPRT: 'Industrial',
  CSX: 'Industrial',
  CTAS: 'Industrial',
  DE: 'Industrial',
  DOV: 'Industrial',
  EMR: 'Industrial',
  ETN: 'Industrial',
  EFX: 'Industrial',
  EXPD: 'Industrial',
  FAST: 'Industrial',
  FBHS: 'Industrial',
  FDX: 'Industrial',
  GD: 'Industrial',
  GE: 'Industrial',
  GNRC: 'Industrial',
  GWW: 'Industrial',
  HON: 'Industrial',
  HUBB: 'Industrial',
  HWM: 'Industrial',
  IEX: 'Industrial',
  IR: 'Industrial',
  ITW: 'Industrial',
  J: 'Industrial',
  JBHT: 'Industrial',
  JCI: 'Industrial',
  LDOS: 'Industrial',
  LHX: 'Industrial',
  LMT: 'Industrial',
  MAS: 'Industrial',
  MMM: 'Industrial',
  NDSN: 'Industrial',
  NOC: 'Industrial',
  NSC: 'Industrial',
  ODFL: 'Industrial',
  OTIS: 'Industrial',
  PCAR: 'Industrial',
  PH: 'Industrial',
  PNR: 'Industrial',
  PWR: 'Industrial',
  RHI: 'Industrial',
  ROK: 'Industrial',
  ROL: 'Industrial',
  RSG: 'Industrial',
  RTX: 'Industrial',
  SNA: 'Industrial',
  SWK: 'Industrial',
  TDG: 'Industrial',
  TDY: 'Industrial',
  TT: 'Industrial',
  TXT: 'Industrial',
  UNP: 'Industrial',
  UPS: 'Industrial',
  URI: 'Industrial',
  VRSK: 'Industrial',
  WAB: 'Industrial',
  WM: 'Industrial',
  XYL: 'Industrial',

  // Energy
  APA: 'Energy',
  BKR: 'Energy',
  COP: 'Energy',
  CTRA: 'Energy',
  CVX: 'Energy',
  DVN: 'Energy',
  EOG: 'Energy',
  EQT: 'Energy',
  FANG: 'Energy',
  HAL: 'Energy',
  HES: 'Energy',
  KMI: 'Energy',
  MPC: 'Energy',
  MRO: 'Energy',
  OKE: 'Energy',
  OXY: 'Energy',
  PSX: 'Energy',
  PXD: 'Energy',
  SLB: 'Energy',
  TRGP: 'Energy',
  VLO: 'Energy',
  WMB: 'Energy',
  XOM: 'Energy',

  // Utilities
  AEE: 'Utility',
  AEP: 'Utility',
  AES: 'Utility',
  ATO: 'Utility',
  AWK: 'Utility',
  CEG: 'Utility',
  CMS: 'Utility',
  CNP: 'Utility',
  D: 'Utility',
  DTE: 'Utility',
  DUK: 'Utility',
  ED: 'Utility',
  EIX: 'Utility',
  ES: 'Utility',
  ETR: 'Utility',
  EVRG: 'Utility',
  EXC: 'Utility',
  FE: 'Utility',
  LNT: 'Utility',
  NEE: 'Utility',
  NI: 'Utility',
  NRG: 'Utility',
  PCG: 'Utility',
  PEG: 'Utility',
  PNW: 'Utility',
  PPL: 'Utility',
  SO: 'Utility',
  SRE: 'Utility',
  WEC: 'Utility',
  XEL: 'Utility',

  // Materials
  ALB: 'Material',
  AMCR: 'Material',
  APD: 'Material',
  AVY: 'Material',
  CE: 'Material',
  CF: 'Material',
  CTVA: 'Material',
  DD: 'Material',
  DOW: 'Material',
  ECL: 'Material',
  EMN: 'Material',
  FCX: 'Material',
  FMC: 'Material',
  IFF: 'Material',
  IP: 'Material',
  LIN: 'Material',
  LYB: 'Material',
  MLM: 'Material',
  MOS: 'Material',
  NEM: 'Material',
  NUE: 'Material',
  PKG: 'Material',
  PPG: 'Material',
  SEE: 'Material',
  SHW: 'Material',
  STLD: 'Material',
  VMC: 'Material',
  WRK: 'Material',
  WY: 'Material',

  // Real Estate
  AMT: 'Real Estate',
  ARE: 'Real Estate',
  AVB: 'Real Estate',
  BXP: 'Real Estate',
  CBRE: 'Real Estate',
  CCI: 'Real Estate',
  CPT: 'Real Estate',
  DLR: 'Real Estate',
  EQIX: 'Real Estate',
  EQR: 'Real Estate',
  ESS: 'Real Estate',
  EXR: 'Real Estate',
  FRT: 'Real Estate',
  HST: 'Real Estate',
  INVH: 'Real Estate',
  IRM: 'Real Estate',
  KIM: 'Real Estate',
  MAA: 'Real Estate',
  O: 'Real Estate',
  PEAK: 'Real Estate',
  PLD: 'Real Estate',
  PSA: 'Real Estate',
  REG: 'Real Estate',
  SBAC: 'Real Estate',
  SPG: 'Real Estate',
  UDR: 'Real Estate',
  VICI: 'Real Estate',
  VTR: 'Real Estate',
  WELL: 'Real Estate',
};
