name: 'Generate Labels'

on:
  pull_request:
    types: [opened, edited, synchronize]

permissions:
  contents: read
  pull-requests: write

jobs:
  label:
    name: 'Label PR based on title'
    runs-on: ubuntu-latest
    steps:
      - name: 'Apply labels'
        uses: srvaroa/labeler@v1.11
        env:
          GITHUB_TOKEN: ${{ github.token }}
